### ISSUE TITLE
Reflection: Mirror is now documented

### ISSUE THREAD

**Issue by mathonsunday** [ksm/SwiftInFlux#100]
[Mirror was added to the Swift Standard Library Reference on 7/21/2015.](https://developer.apple.com/library/prerelease/ios/documentation/Swift/Reference/Swift_Mirror_Structure/index.html#//apple_ref/swift/struct/s:VSs6Mirror) The article Simple Reflection in Swift is from 2014. I'm just learning about these these concepts in Swift but happy to make a PR once I have a better idea of how I would change the Reflection section.

**Comment by chakrit** [comment]
nice, really needed this.

**Comment by jklausa** [comment]
As per #102, the project is no longer maintained. 

Thanks for your contributions and sorry we didn't got around to incorporating them.
