### ISSUE TITLE
Overriding declarations from extensions works with @objc

### ISSUE THREAD

**Issue by Pretz** [ksm/SwiftInFlux#74]
Found via http://stackoverflow.com/a/27109202/195691, adding `@objc` to extension properties and methods allows them to be overridden:

```swift
import Foundation
class Base { }

extension Base {
    @objc var foo: String { return "foo" }
}

class Sub: Base {
    override var foo: String { return "FOO" } // This no longer errors
}
```
This may be a bug in the `@objc` implementation, however, as when I try this in an iOS Playground I get a runtime error when instantiating `Sub()`, but it works in an OS X playground and in the command line `swift` REPL.

**Comment by conradwt** [comment]
@Pretz I would recommend submitting a bug report with test case(s) to Apple:

```
http://bugreport.apple.com
```

**Comment by jklausa** [comment]
I'm not sure if that's even a bug in the compiler, bug in the way that methods are dispatched between the two runtimes, or an actual feature of the language.

I'd say this is weird enough that it's not a clear-cut 'bug' and probably will get addressed somewhere down the line. WDYT @radex?

**Comment by radex** [comment]
Sounds to me like a side-effect of how the objc runtime. I think it's worth to mention on SiF.

**Comment by conradwt** [comment]
@Pretz I just wanted you to know that I submitted an actual bug report to Apple regarding this issue with the appropriate test cases because the Objective-C runtime exhibited different behavior when used with different UI layers (i.e. Cocoa Touch vs Cocoa) and it's not clear as to which environment correct.  However, the exhibited behavior within the Swift language IMO should be consistent in both environments.

**Comment by Pretz** [comment]
@conradwt Thanks for the update, and thanks for putting together a radar!

**Comment by jklausa** [comment]
@conradwt mind sharing the radar on http://openradar.appspot.com/page/1 ?

**Comment by conradwt** [comment]
Here's the associated radar for the bug report (i.e. bugreport.apple.com) that was filed:

```
rdar://problem/19411242
```
