### ISSUE TITLE
XCode 6 Beta 4 change on convenience initialisers?

### ISSUE THREAD

**Issue by danielgomezrico** [ksm/SwiftInFlux#88]
I just installed Xcode 6 beta 4 and my convenience inits don't work anymore.

It says `Could not find an overload for init that accepts the supplied arguments`

`class MyController: UIViewController{

	convenience init() {
		self.init(nibName: "CreditOptionsView", bundle: nil)
	}

}`

It happened too with a convenience initialiser for UIViewController `self.init(rootViewController: viewController)`

Why?
It was working in the `Xcode 3 beta 2`

**Comment by danielgomezrico** [comment]
I solve it writing an empty override of the function, I don't know why swift can't find it. ex:

	class MyNavigationController: UINavigationController {

	    override init(rootViewController: UIViewController) {
			super.init(rootViewController: rootViewController)
		}
		
		convenience init() {
	    	self.init(rootViewController: UIViewController())
		}
	}

Same thing happened in a convenience init for UINavigationController and solved adding again the empty override:

	class MyNavigationController: UINavigationController {

	    override init(rootViewController: UIViewController) {
	        super.init(rootViewController: rootViewController)
	    }

	    convenience init() {
	        self.init(rootViewController: UIViewController())
	    }
	}

**Comment by danielgomezrico** [comment]
Because all convenience initialisers are not inherited anymore?

**Comment by jklausa** [comment]
As per #102, the project is no longer maintained. 

Thanks for your contributions and sorry we didn't got around to incorporating them.
